# Generated by Django 5.2.8 on 2025-11-24 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='perfil',
            field=models.CharField(choices=[('T', 'Terapeuta'), ('U', 'Usuario')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
